### ISSUE TITLE
Expand item being clipped

### ISSUE THREAD

**Issue by devriesb13** [sbaeumlisberger/VirtualizingWrapPanel#15]
Using the samples demo app

When items are only in the first row, the expand item template is being clipped. See image

![image](https://user-images.githubusercontent.com/10214916/113094194-9aeb5200-9234-11eb-93aa-8da1a143f2aa.png)

**Comment by sbaeumlisberger** [comment]
Hi, thanks for reporting this issue. I have investigated it and have committed a fix right now.

**Comment by devriesb13** [comment]
thanks, this has fixed the issue on my end also. Will you be deploying and nuget package update for this?

**Comment by sbaeumlisberger** [comment]
Glad to hear that. I will publish a updated nuget package soon.

**Comment by sbaeumlisberger** [comment]
The updated package is online: https://www.nuget.org/packages/VirtualizingWrapPanel/1.5.4
