### ISSUE TITLE
[Bug] Disable VerticalScrollBar will make VirtualizingWrapPanel behave weird

### ISSUE THREAD

**Issue by CoelWu** [sbaeumlisberger/VirtualizingWrapPanel#16]
**Describe your issue**
I'm trying to hide ScrollViewer's VerticalScrollBar for my ListView. When I try to set the ``ScrollViewer.VerticalScrollBarVisibility`` to hidden, a lot of items disappeared and I can scroll to empty areas. See this gif for a clear view of what's happening.

![example](https://user-images.githubusercontent.com/76829607/113284242-f17f8b80-931b-11eb-8a9a-5688664b1636.gif)

Thanks for helping!

**Version Info**
Package Version: 1.5.3
.NET Version: .NET 5
Platform: WPF
OS Version: Windows 10 Build 18363.1440

**Comment by sbaeumlisberger** [comment]
Hey, thanks for reporting this issue. I have investigated it and I have commited a fix just now.

**Comment by sbaeumlisberger** [comment]
Here you can download a package with the fix. Please let me know if this solves your issue.
[VirtualizingWrapPanel.1.5.4-dev.zip](https://github.com/sbaeumlisberger/VirtualizingWrapPanel/files/6248874/VirtualizingWrapPanel.1.5.4-dev.zip)

**Comment by CoelWu** [comment]
Hi, thank you so much for helping and fixing! I will try it as soon as possible.

**Comment by CoelWu** [comment]
Hi @sbaeumlisberger, this bug was fixed perfectly! Thank you so much for helping! :D

**Comment by sbaeumlisberger** [comment]
The updated package is online: https://www.nuget.org/packages/VirtualizingWrapPanel/1.5.4

**Comment by CoelWu** [comment]
> The updated package is online: https://www.nuget.org/packages/VirtualizingWrapPanel/1.5.4

Got it! Thank you so much for helping again! :D
