### ISSUE TITLE
[feature] Allow to set a fixed item spacing

### ISSUE THREAD

**Issue by GenmTim** [sbaeumlisberger/VirtualizingWrapPanel#17]
[https://github.com/HandyOrg/HandyControl](url) UniformSpacingPanel

![image](https://user-images.githubusercontent.com/69684108/119761058-b645a700-bedd-11eb-8fd6-ab08587dca8e.png)

**Comment by sbaeumlisberger** [comment]
Hi,

the VirtualizingWrapPanel currently supports four different spacing modes. The way I see it, `SpacingMode.BetweenItemsOnly` is exactly what you are suggesting. You can find the SpacingMode documentation [here](https://sbaeumlisberger.github.io/VirtualizingWrapPanel/api/WpfToolkit.Controls.SpacingMode.html).

Changing the spacing mode is very simple as you can see in the following code snippet:
`<vwp:VirtualizingWrapPanel  SpacingMode="BetweenItemsOnly" />`

Let me know if this helps or what the difference to your suggestion is.

**Comment by GenmTim** [comment]
But if I use `Stretch Items`, I can't set a fixed spacing.

If you can use 'spacing' to specify spacing like this, I think it will be more convenient and concise

```xml
<hc:UniformSpacingPanel Spacing="10">
    <Button Content="{ex:Lang Key={x:Static langs:LangKeys.ContentDemoStr}}"/>
    <Button Content="{ex:Lang Key={x:Static langs:LangKeys.ContentDemoStr}}"/>
    <Button Content="{ex:Lang Key={x:Static langs:LangKeys.ContentDemoStr}}"/>
    <Button Content="{ex:Lang Key={x:Static langs:LangKeys.ContentDemoStr}}"/>
</hc:UniformSpacingPanel>
```

Instead of using margin to reserve space.

![image](https://user-images.githubusercontent.com/69684108/119943871-30515b00-bfc6-11eb-865d-b2461755dbf3.png)

（Excuse me, my English is poor.）

**Comment by sbaeumlisberger** [comment]
Okay now I understand what you want to achieve. There is unfortunately no build in API which allows that.

But you can set a uniform margin on the list view items and a corresponding negative margin on the VirtualizingWrapPanel.

here is a short sample:

```
<ListView>
    <ListView.ItemContainerStyle> 
        <Style TargetType="{x:Type ListViewItem}">
            <Setter Property="Margin" Value="20,0,20,0"/>
            <Setter Property="HorizontalContentAlignment" Value="Stretch"/>
            <Setter Property="VerticalContentAlignment" Value="Stretch"/>
        </Style>
    </ListView.ItemContainerStyle>
    <ListView.ItemsPanel>
        <ItemsPanelTemplate>
            <wpftk:VirtualizingWrapPanel
                Margin="-20,2,-20,0"
                StretchItems="True" />
        </ItemsPanelTemplate>
    </ListView.ItemsPanel>
</ListView>
```

This will look like that:

![image](https://user-images.githubusercontent.com/56502702/119993211-9ee4e780-bfcb-11eb-83ed-1ed70822068f.png)

**Comment by sbaeumlisberger** [comment]
I am considering adding this functionality in a future release.

**Comment by GenmTim** [comment]
Thank you for taking my advice! :smile:
