### ISSUE TITLE
Divided by Zero exception at BringIndexIntoView

### ISSUE THREAD

**Issue by milos12345** [sbaeumlisberger/VirtualizingWrapPanel#19]
I am getting Divided by Zero exception at
```
protected override void BringIndexIntoView(int index)
{
    var offset = (index / itemsPerRowCount) * GetHeight(childSize);
```
where `itemsPerRowCount` is zero

I am hosting it in a ListBox
```
<ListBox 
      ItemTemplate="{StaticResource ItemTemplate}"
      >
      <ListBox.Template>
          <ControlTemplate TargetType="ListBox">
              <ScrollViewer >
                  <wpftk:VirtualizingWrapPanel IsItemsHost="True" ItemSize="96,96"  Orientation="Vertical"/>
              </ScrollViewer>
          </ControlTemplate>
          
      </ListBox.Template>
  </ListBox>
```
I have tried adding ListBox in your example but it was fine. 
It happens only only the first time the items are listed in my project (they already appear as a grid a moment before throwing).
For now I did a quick fix:
```
protected override void BringIndexIntoView(int index)
{
    if (itemsPerRowCount == 0)
        return;
```
It is a complex project and everything is custom templates so at this time I don't know what breaks it.

**Version Info**
Package Version - cloned today
.NET Version: .NET Framework 4.8]
OS Version: Windows 10 Build 19042.985

**Comment by sbaeumlisberger** [comment]
Hi, I had a look at you issue but I have no idea why this happens.

Are using the ListBox.ScrollIntoView method anywhere?

It would be very helpful if you could set a breakpoint in the BringIndexIntoView method and look up in the call stack why the method is called.

**Comment by milos12345** [comment]
I didn't do versioning well here, so I was not able to do it again, but back then I've tried setting up a breakpoint but it didn't show me anything before that point in the Stack Trace. I have `ScrollIntoView` on a few places but I did find that I had `ScrollIntoView(0)` right after populating ObservableCollection that is bound to the ListBox with `VirtualizingWrapPanel` which may have been responsible for this but after many changes it is not even hitting that point anymore, but I will keep the line checking for `itemsPerRowCount` just in case.

**Comment by sbaeumlisberger** [comment]
Okay, I'll close this issue for now. If you can reproduce the issue and have more information about what is causing it, feel free to open a new issue.
