### ISSUE TITLE
Q: Has the VirtualizingWrapPanel been tested with item selection (remove/add etc.)

### ISSUE THREAD

**Issue by nietras** [sbaeumlisberger/VirtualizingWrapPanel#20]
The `VirtualizingWrapPanel` looks great and appears to be functional, but I wonder how much this has been tested with regard to item selection and removal etc.? 

I have used quite a few of these panels from different sources and many have issues with item selection when this selection goes out of view etc. I have done a bit of testing of this, but it can be hard to trigger the issue, so was just wondering if this has been touched upon before?

Could item selection and remove (selected items) be added to the sample app for example?

**Comment by sbaeumlisberger** [comment]
The VirtualizingWrapPanel is not specifically tested in regard of item selection. But it works without problems in many personal projects and I also never heard from other people having issues with the item selection. The selection going out of view definitely works fine.

You can already try out the item selection in the samples app. Do you miss anything specific here?

If you should find any issues with item selection, feel free open to an issue.
