### ISSUE TITLE
Please add ItemWidth and ItemHeight instead of ItemSize

### ISSUE THREAD

**Issue by bezzad** [sbaeumlisberger/VirtualizingWrapPanel#23]
Hi,
I use the MVVM and I can't to using `System.Drawing.Size` in the ViewModel object. For [this](https://github.com/jbe2277/waf/wiki/Layered-Architecture#5-application-layer) reason.
Can you add ItemWidth and ItemHeight dependency properties to the library?

**Comment by sbaeumlisberger** [comment]
Hi,

as you can see [here](https://sbaeumlisberger.github.io/VirtualizingWrapPanel/api/WpfToolkit.Controls.VirtualizingWrapPanel.html#WpfToolkit_Controls_VirtualizingWrapPanel_ItemSize)  the ItemSizeproperty of the VirtualizingWrapPanel is of the type `System.Windows.Size`, not `System.Drawing.Size`. According to your link it should be fine to use this type in your view models. 

Anyway you could use a `IValueConverter` to convert any other type to  the required `System.Windows.Size`.

I hope that helps :)

**Comment by bezzad** [comment]
That's awesome. thanks
