### ISSUE TITLE
Maximising does not hide the scrollbar

### ISSUE THREAD

**Issue by Tomtomijk** [sbaeumlisberger/VirtualizingWrapPanel#25]
**Describe your issue**
When maximising a window with a scroll bar, the scroll bar does not disappear until item is clicked on

**Version Info**
Package Version: 1.5.1-1.5.4
.NET Version: .NET Core 3.1
OS Version: [Windows 10 Build 19042.1237]

![image](https://user-images.githubusercontent.com/11030161/137699844-ed1cff78-456c-4aae-ad20-b8da0a538759.png)

![image](https://user-images.githubusercontent.com/11030161/137700045-8072be2d-39c0-4423-9c22-dd238f19f028.png)

![image](https://user-images.githubusercontent.com/11030161/137700136-68d459c4-59e4-4264-a323-302bc9b836ea.png)

**Comment by sbaeumlisberger** [comment]
Thanks for reporting this issue. I will look at it as soon as possible.

**Comment by sbaeumlisberger** [comment]
I have published a new nuget package fixing this issue: https://www.nuget.org/packages/VirtualizingWrapPanel/1.5.5
