### ISSUE TITLE
Only first tile renders after latest update

### ISSUE THREAD

**Issue by julesx** [sbaeumlisberger/VirtualizingWrapPanel#26]
**Describe your issue**
Since the latest update, when i load a large amount of items, the first tile and only the first tile renders immediately.
Then there is a big delay, and the rest of the tiles MAY load. sometimes they just don't. 
Applying a filter (eg triggering some property change notifications) to the source collection resolves the issue.

**Version Info**
Package Version 1.5.5

**Comment by sbaeumlisberger** [comment]
sorry to hear that. I will have a look at it and get back to you.

Could you provide some code snippet to show how you use the control?

**Comment by julesx** [comment]
`<ListBox x:Class="PG.UserControls.ListBoxPgItems"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008" 
    xmlns:classes="clr-namespace:WPF.Core.Classes;assembly=WPF.Core"
    mc:Ignorable="d" 
         SelectionMode="Extended"
    Style="{StaticResource MaterialDesignListBox}"
    xmlns:controls="clr-namespace:WpfToolkit.Controls;assembly=VirtualizingWrapPanel" 
         xmlns:i="http://schemas.microsoft.com/xaml/behaviors" 
         xmlns:behaviors="clr-namespace:WPF.Core.Behaviors;assembly=WPF.Core"
         d:DesignHeight="450" d:DesignWidth="800">

    <i:Interaction.Behaviors>
        <behaviors:MultiSelectionBehavior SelectedItems="{Binding SelectedPgItems}" />
    </i:Interaction.Behaviors>

    <ListBox.Resources>
        <ResourceDictionary>
            
            <Style x:Key="ListBoxPgItemStyle" BasedOn="{StaticResource MaterialDesignCardsListBoxItem}" TargetType="ListBoxItem">
                <Setter Property="Height" Value="{Binding DataContext.ListBoxItemHeight, Source={classes:RootObject}}" />
                <Setter Property="Width" Value="{Binding DataContext.ListBoxItemWidth, Source={classes:RootObject}}" />
                <EventSetter Event="PreviewMouseDoubleClick" Handler="ListBoxItem_PreviewMouseDoubleClick" />

            </Style>
        </ResourceDictionary>
    </ListBox.Resources>

    <ListBox.ItemsPanel>
        <ItemsPanelTemplate>
            <controls:VirtualizingWrapPanel SpacingMode="StartAndEndOnly" />
        </ItemsPanelTemplate>
    </ListBox.ItemsPanel>

</ListBox>`

**Comment by julesx** [comment]
`<ListBox x:Class="PG.UserControls.ListBoxPgItems"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008" 
    xmlns:classes="clr-namespace:WPF.Core.Classes;assembly=WPF.Core"
    mc:Ignorable="d" 
         SelectionMode="Extended"
    Style="{StaticResource MaterialDesignListBox}"
    xmlns:controls="clr-namespace:WpfToolkit.Controls;assembly=VirtualizingWrapPanel" 
         xmlns:i="http://schemas.microsoft.com/xaml/behaviors" 
         xmlns:behaviors="clr-namespace:WPF.Core.Behaviors;assembly=WPF.Core"
         d:DesignHeight="450" d:DesignWidth="800">

    <i:Interaction.Behaviors>
        <behaviors:MultiSelectionBehavior SelectedItems="{Binding SelectedPgItems}" />
    </i:Interaction.Behaviors>

    <ListBox.Resources>
        <ResourceDictionary>
            
            <Style x:Key="ListBoxPgItemStyle" BasedOn="{StaticResource MaterialDesignCardsListBoxItem}" TargetType="ListBoxItem">
                <Setter Property="Height" Value="{Binding DataContext.ListBoxItemHeight, Source={classes:RootObject}}" />
                <Setter Property="Width" Value="{Binding DataContext.ListBoxItemWidth, Source={classes:RootObject}}" />
                <EventSetter Event="PreviewMouseDoubleClick" Handler="ListBoxItem_PreviewMouseDoubleClick" />

            </Style>
        </ResourceDictionary>
    </ListBox.Resources>

    <ListBox.ItemsPanel>
        <ItemsPanelTemplate>
            <controls:VirtualizingWrapPanel SpacingMode="StartAndEndOnly" />
        </ItemsPanelTemplate>
    </ListBox.ItemsPanel>

</ListBox>
`

**Comment by julesx** [comment]
<ListBox x:Class="PG.UserControls.ListBoxPgItems"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008" 
    xmlns:classes="clr-namespace:WPF.Core.Classes;assembly=WPF.Core"
    mc:Ignorable="d" 
         SelectionMode="Extended"
    Style="{StaticResource MaterialDesignListBox}"
    xmlns:controls="clr-namespace:WpfToolkit.Controls;assembly=VirtualizingWrapPanel" 
         xmlns:i="http://schemas.microsoft.com/xaml/behaviors" 
         xmlns:behaviors="clr-namespace:WPF.Core.Behaviors;assembly=WPF.Core"
         d:DesignHeight="450" d:DesignWidth="800">

    <i:Interaction.Behaviors>
        <behaviors:MultiSelectionBehavior SelectedItems="{Binding SelectedPgItems}" />
    </i:Interaction.Behaviors>

    <ListBox.Resources>
        <ResourceDictionary>
            
            <Style x:Key="ListBoxPgItemStyle" BasedOn="{StaticResource MaterialDesignCardsListBoxItem}" TargetType="ListBoxItem">
                <Setter Property="Height" Value="{Binding DataContext.ListBoxItemHeight, Source={classes:RootObject}}" />
                <Setter Property="Width" Value="{Binding DataContext.ListBoxItemWidth, Source={classes:RootObject}}" />
                <EventSetter Event="PreviewMouseDoubleClick" Handler="ListBoxItem_PreviewMouseDoubleClick" />

            </Style>
        </ResourceDictionary>
    </ListBox.Resources>

    <ListBox.ItemsPanel>
        <ItemsPanelTemplate>
            <controls:VirtualizingWrapPanel SpacingMode="StartAndEndOnly" />
        </ItemsPanelTemplate>
    </ListBox.ItemsPanel>

</ListBox>

**Comment by sbaeumlisberger** [comment]
just fixed: https://www.nuget.org/packages/VirtualizingWrapPanel/1.5.6

**Comment by julesx** [comment]
thanks. fixed.
