### ISSUE TITLE
Freeze when trying to moving up and down with keyboard keys

### ISSUE THREAD

**Issue by alo00** [sbaeumlisberger/VirtualizingWrapPanel#29]
When tiles are bigger than WrapPanel size, trying to use keyboard down arrow to move to next row will freeze the app.

This can be easily reproduced with your sample app.

- Reduce the windows size to have the tile slightly higher than the Panel size. (see bellow picture)
- Use the keyboard arrows key. You can go right and left with no problem, going down => freeze.

I noticed in my app there is a loop constantly calling ScrollViewer.ScrollChanged event with a vertical shift of +200, -200, +200, -200....

Regards

![image](https://user-images.githubusercontent.com/90386527/145586047-238bb812-8c4c-4c7f-b68a-2beb665f034c.png)

Package Version   1.5 -> 1.5.6
.NET Version: netcoreapp3.1 (Your sample application)
OS Version:  Windows 10

**Comment by sbaeumlisberger** [comment]
Thanks for reporting this issue. I was able to reproduce the problem and I am working on a solution.

**Comment by sbaeumlisberger** [comment]
Bug is fixed and I have published a updated [nuget package](https://www.nuget.org/packages/VirtualizingWrapPanel/1.5.7). The sample application will also be updated soon.

**Comment by alo00** [comment]
Thank's a lot, working perfectly! :-)
