### ISSUE TITLE
When scrolling up and down quickly, some pictures will not be loaded. How to solve this problem?

### ISSUE THREAD

**Issue by Akise** [sbaeumlisberger/VirtualizingWrapPanel#33]
When scrolling up and down quickly, there will be pictures that are not loaded and display blank. They will be loaded later. How to solve this problem?
Can I set up a pre render part of the picture to solve the problem?

Video demo (use local player after downloading):
https://user-images.githubusercontent.com/3281973/151739219-76541fdb-9c08-4acf-99a5-e0b030d89d37.mp4

Code:
[csTest8.zip](https://github.com/sbaeumlisberger/VirtualizingWrapPanel/files/7968091/csTest8.zip)

**Comment by sbaeumlisberger** [comment]
Hi have you tried to increase the caching? You can use the attached properties VirtualizingPanel.CacheLength and VirtualizingPanel.CacheLengthUnit.

**Comment by CodingOctocat** [comment]
For my program, when I set the cache mode to Recycling, then the images will be misplaced (shuffled) and I have to use the Standard mode.

**Comment by sbaeumlisberger** [comment]
Closing the issue now. Please open a new issue if you still have problems.

@CodingOctocat When using the recycling mode the item are reused so you have to clear them by yourself. If you need further help with the recycling mode feel free to let me know.
