### ISSUE TITLE
Arrange error when item keep aspect ratio.

### ISSUE THREAD

**Issue by CodingOctocat** [sbaeumlisberger/VirtualizingWrapPanel#36]
I'm developing an image gallery that can be previewed by thumbnails just like `Explorer`.

```XAML
<wpftk:VirtualizingItemsControl
    Margin="0,2,0,0"
    ItemTemplate="{StaticResource ItemTemplate}"
    VirtualizingPanel.CacheLengthUnit="Item"
    VirtualizingPanel.CacheLength="1,1"
    VirtualizingPanel.ScrollUnit="Pixel"
    VirtualizingPanel.VirtualizationMode="Standard"
    ScrollViewer.HorizontalScrollBarVisibility="Disabled"
    ScrollViewer.VerticalScrollBarVisibility="Auto">
    <ItemsControl.ItemsPanel>
        <ItemsPanelTemplate>
            <wpftk:VirtualizingWrapPanel
                Orientation="Vertical"
                SpacingMode="None" 
                StretchItems="True">
        </ItemsPanelTemplate>
    </ItemsControl.ItemsPanel>
</wpftk:VirtualizingItemsControl>
```
ItemTemplate:
```XAML
<DataTemplate x:key="ItemTemplate">
    <mycontrol:MyThumbnail ImageSource="xxx/yyy/zzz.jpg"/>
</DataTemplate>
```
Bind the `Height` of the `MyThumbnail` control to the `Width` so that it always remains `16:9`.
And Arrange error(I will re-upload screenshots of the real situation when I have time):
![微信截图_20220316085741](https://user-images.githubusercontent.com/7220248/158496079-ab4af5f9-0f20-4b81-9cc7-99eca0888055.png)

**I guess the reason lies in the dynamically changing height of the item.**

I have tried the following solution and it works fine (but it not support virtualization):
[WrapPanel with full width columns](https://blog.jonstodle.com/wrappanel-with-full-width-columns/)
[UniformMinWidthWrapPanel](https://gist.github.com/jonstodle/24f508591066521acbae)

**Version Info**
Package Version 1.5.7
.NET Version: .NET 6
OS Version: Win11

**Comment by CodingOctocat** [comment]
Actual results:
![Snipaste_2022-03-16_18-10-50](https://user-images.githubusercontent.com/7220248/158567338-302e5f32-9a34-4fe7-b7fd-6a7f20d450b0.png)
![Snipaste_2022-03-16_18-10-41](https://user-images.githubusercontent.com/7220248/158567349-3ab67714-ff90-4d63-839a-3443b7fe78cb.png)

**Comment by CodingOctocat** [comment]
![Snipaste_2022-03-16_18-59-04](https://user-images.githubusercontent.com/7220248/158575239-1e02b5fa-a1cd-43a8-a383-ff3f27900ab8.png)

**Comment by sbaeumlisberger** [comment]
Hi, in order to support virtualization the panel currently requires all items to have the same size. There is already an issue with the aim to allow different sized items: https://github.com/sbaeumlisberger/VirtualizingWrapPanel/issues/22 Unfortunately, I don't have time to work on it actively at the moment. Hopefully, this will change in the summer.

In order to solve your issue right now you have to make sure that all items are sized equally. Therefore can use the ItemSize property or set some size constraints on item template.
