### ISSUE TITLE
Some simple changes can make it much more performant

### ISSUE THREAD

**Issue by seanhalliday** [sbaeumlisberger/VirtualizingWrapPanel#40]
**Performance*
When recycling controls, do not remove them from InternalChilcren (just hide them).  Take a look at how VirtualizingStackPanel keeps them in InternalChildren and keeps a _realizedList of controls that match the ones known about in the generator's recycler.  Sorry I can't contribute the code but I have my own version not based on this and that update made a big performance improvement.  
**Version Info**
Package Version [e.g. 1.5.2]
.NET Version: [e.g. .NET Framework 4.7.2]
OS Version: [e.g. Windows 10 Build 19041.508]

**Comment by sbaeumlisberger** [comment]
Thanks for the suggestion. This is already part of the refactoring for the next version I am working on.

**Comment by sbaeumlisberger** [comment]
The 2.0 version has just been released: https://www.nuget.org/packages/VirtualizingWrapPanel/2.0.0
