### ISSUE TITLE
scroll bar visibility

### ISSUE THREAD

**Issue by GuoFeng888** [sbaeumlisberger/VirtualizingWrapPanel#44]
When Orientation is set to Vertical, for some reason I need to set the width of the VirtualizingWrapPanel to be larger than the width of the ItemsControl to make the horizontal scroll bar visible. I hope the author can improve the control to support this requirement.

**Comment by sbaeumlisberger** [comment]
The visibility of the scroll bar can be controlled as usual by the attached properties `ScrollViewer.HorizontalScrollBarVisibility` and `ScrollViewer.VerticalScrollBarVisibility`. 

Example:
`<ItemsControl ScrollViewer.HorizontalScrollBarVisibility="Visible" ...`

**Comment by GuoFeng888** [comment]
I modified your demo for testing before, but it could not be displayed normally.This is my code:
 <TabItem Header="ItemSize">
                <DockPanel Margin="8,0,8,2">
                    <TextBlock 
                        DockPanel.Dock="Top"    
                        Text="A VirtualizingWrapPanel with an ItemSize of 200x200 used by a ListView as ItemsPanel." />
                    <ListView
                        Margin="0,2,0,0"
                        SelectionMode="Single"
                        ItemTemplate="{StaticResource ItemTemplate}"
                        ScrollViewer.HorizontalScrollBarVisibility="Visible"
                        ScrollViewer.VerticalScrollBarVisibility="Visible"
                        >
                        <ListView.ItemsPanel>
                            <ItemsPanelTemplate>
                                <wpftk:VirtualizingWrapPanel 
                                    Width="2000" 
                                    Orientation="Vertical" 
                                    HorizontalAlignment="Left"
                                    SpacingMode="None" />
                            </ItemsPanelTemplate>
                        </ListView.ItemsPanel>
                    </ListView>
                </DockPanel>
            </TabItem>
Today I created a new test demo, horizontal scrolling can display, but scroll to the far right, will automatically scroll to the left.This is my code:
 <ListView 
            SelectionMode="Single" 
            ItemsSource="{Binding Datas}"
            ScrollViewer.HorizontalScrollBarVisibility="Auto"
            ScrollViewer.VerticalScrollBarVisibility="Auto"
            >
            <ListView.ItemTemplate>
                <DataTemplate>
                    <TextBlock Text="{Binding Name}" Width="100"/>
                </DataTemplate>
            </ListView.ItemTemplate>
            <ListView.ItemsPanel>
                <ItemsPanelTemplate>
                    <wpftk:VirtualizingWrapPanel 
                        Width="2000" 
                        Orientation="Vertical" 
                        HorizontalAlignment="Left"
                        SpacingMode="None" />
                </ItemsPanelTemplate>
            </ListView.ItemsPanel>
        </ListView>

**Comment by sbaeumlisberger** [comment]
Thanks for the example. I was able to reproduce you issue.

**Comment by sbaeumlisberger** [comment]
I looked into the problem and found that this is a limitation of the WPF framework. When you set one of the WPF size properties (With, MinWidth, MaxWidth), the available size  is no longer passed to the VirtualizingWrapPanel implementation. So unfortunately there is no way to fix this without some heavy quirks. If you really need a solution for this issue you could extend my implementation and add some special handling to the MeasureOverride method. For example like this:

```  
protected override Size MeasureOverride(Size availableSize)
{
    if (ScrollOwner != null && ScrollOwner.ActualWidth != 0 && ScrollOwner.ActualHeight != 0)
    {
        availableSize = new Size(
            Math.Min(availableSize.Width, ScrollOwner.ActualWidth), 
            Math.Min(availableSize.Height, ScrollOwner.ActualHeight));
    }
    return base.MeasureOverride(availableSize);
}
```
You must also register an event handler to be notified when the size of the scroll viewer changes, and then call the InvalidateMeasure method. Otherwise, it will not work. If properties like margin or padding are used, they must be handled manually in your code.

**Comment by GuoFeng888** [comment]
Thank you for your solution,I'll  try it.
