### ISSUE TITLE
Style SelectedItem

### ISSUE THREAD

**Issue by AsDotNet** [sbaeumlisberger/VirtualizingWrapPanel#46]
Hi,

is it possible the set the style of a selected item in the WrapPanel?

**Comment by sbaeumlisberger** [comment]
Of course it's possible. You can add a Style with a trigger, for example:

<Style TargetType="{x:Type ListViewItem}">
   <Style.Triggers>
      <Trigger Property="IsSelected" Value="true" >
        <Setter Property="..." Value="..." />
        ... more setters ...
      </Trigger>
   </Style.Triggers>
</Style>

**Comment by AsDotNet** [comment]
Thanks! ListViewItem was the hint I needed.
