### ISSUE TITLE
When download your solution and trying to compile in vs2019, nothing works

### ISSUE THREAD

**Issue by eriveraa** [sbaeumlisberger/VirtualizingWrapPanel#5]
Please your help. I have downloaded your solution but i am not able to compile neither to run.
I also downloaded your executable demos, but they don't run in Windows 10. Am i missing something?
Thanks in advance.

**Comment by eriveraa** [comment]
Also, the Samples webpage is not working :(

**Comment by sbaeumlisberger** [comment]
Hi, 

do build the project make sure you have installed the .NET Core 3.0 SDK.

Indeed there is a problem with the samples download page. I will have a look at that soon.

In the meantime an older version of the samples application can be downloaded [here](https://gitlab.com/sbaeumlisberger/virtualizing-wrap-panel/-/raw/master/downloads/VirtualizingWrapPanelSamples-win-x64.exe).

**Comment by sbaeumlisberger** [comment]
The samples download page should now work again.

**Comment by eriveraa** [comment]
Hi, i am trying to use your component with  WPF .Net 4.8, do i still need .NET Core 3.0?

**Comment by sbaeumlisberger** [comment]
For using the nuget package you don't need .NET Core. The nuget package ist compatible with every .NET Framework version higher than 4.5. If you just want to use the project in you own app, this is the right way.

But if you want to build the project yourself you need it because the project does multi target .NET Framework 4.5 and NET Core 3.0.

Could you run the updated samples application?

**Comment by eriveraa** [comment]
Hi, i downloaded the 64 bit version from here:
https://github.com/sbaeumlisberger/VirtualizingWrapPanel/blob/master/SamplesApplication.md

However, there is a weird flickering in the application. When i move over the tabs they dissapear, and there is rare behaviour in the UI. Are you aware of that?

**Comment by sbaeumlisberger** [comment]
This issues are new to me. On my machine Windows 10 (19041.450) everything works fine.

**Comment by sbaeumlisberger** [comment]
I'm going to close this issue now. If you still having difficulties using the project, open a new issue with a detailed description.
