### ISSUE TITLE
ScrollIntoView function appear offset when using VirtualizableWrapPanel AllowDifferentSizedItems

### ISSUE THREAD

**Issue by wuyang26** [sbaeumlisberger/VirtualizingWrapPanel#54]
1 run demo
2 select tab "VirtualizableWrapPanel AllowDifferentSizedItems"
3 input number in the ScrollIntoView(Number) textbox, for example: 500 0r 800
4 you can find the listview can not scroll the 500 or 800 block position.

**Comment by sbaeumlisberger** [comment]
That's be design. If you need exact positioning and scrolling with different sized items you have to set the `ItemSizeProvider` property. This is shown in the "VirtualizableWrapPanel AllowDifferentSizedItems Lazy IItemSizeProvider" tab.

More information here: https://github.com/sbaeumlisberger/VirtualizingWrapPanel/blob/master/GettingStarted.md#different-sized-items and here: https://sbaeumlisberger.github.io/VirtualizingWrapPanel/api/WpfToolkit.Controls.IItemSizeProvider.html
