### ISSUE TITLE
How to center wrap panel and left align items

### ISSUE THREAD

**Issue by tstephansen** [sbaeumlisberger/VirtualizingWrapPanel#55]
We recently updated from 1.5.8 to 2.0.4 (now 2.0.5) and we noticed that when there aren't enough items to fill the space the items are now centered in the screen. I've tried adjusting the horizontal alignment of the ListView and the containing Grid with no luck. Is there a way to left align the wrap panel and still have the panel itself centered in the Grid? In 1.5.8 this behavior worked as expected. I'm just not sure what to change to fix this.

Basically I want the wrap panel itself to be centered (so there is even margin on both sides) but if there's only a few items and not enough to take up the available width those items should be left aligned. I'm able to achieve something similar to this with a converter that sets the width of the listview to a proportion of the ActualSize of the containing element. However, when I do this the items are no longer centered. If I change the StretchItems property to true it gets close to what I want but there's too much space between the items (maybe there is a way to set this somewhere that I'm just not seeing?).

On a different note, thank you so much for creating this project because we really needed a wrap panel but when we use the built in one our app can crawl to a slow depending on of the amount of items in it.

**Version Info**
Package Version: 2.0.5
.NET Version: net8.0-windows
OS Version: Windows 11 22631.3296

```xaml
<Style x:Key="DashboardListViewStyle" TargetType="{x:Type ListView}">
    <Setter Property="Margin" Value="0,0,0,12" />
    <Setter Property="HorizontalAlignment" Value="Stretch" />
    <Setter Property="Background" Value="#00FFFFFF" />
    <Setter Property="BorderBrush" Value="#00FFFFFF" />
    <Setter Property="ItemContainerStyle" Value="{DynamicResource DashboardListViewItemStyle}" />
    <Setter Property="ItemsPanel">
        <Setter.Value>
            <ItemsPanelTemplate>
                <vwp:VirtualizingWrapPanel AllowDifferentSizedItems="False" 
                                           CanVerticallyScroll="True"
                                           ItemSize="328,440"
                                           MouseWheelDelta="48"
                                           Orientation="Horizontal"
                                           ScrollLineDelta="16"
                                           SpacingMode="None"
                                           StretchItems="False" />
            </ItemsPanelTemplate>
        </Setter.Value>
    </Setter>
    <Setter Property="VirtualizingPanel.VirtualizationMode" Value="Standard" />
    <Setter Property="VirtualizingPanel.ScrollUnit" Value="Pixel" />
</Style>
```

**Comment by sbaeumlisberger** [comment]
If I understand you issue correctly, it should be sufficient to set the [SpacingMode](https://sbaeumlisberger.github.io/VirtualizingWrapPanel/api/WpfToolkit.Controls.SpacingMode.html) to `StartAndEndOnly`. Keep in mind that this only works properly when `AllowDifferentSizedItems` is false.

I hope that helps, otherwise please provide more information e.g. screenshots or some minimal sample.

**Comment by tstephansen** [comment]
That fixed it. Thank you for the help!
