### ISSUE TITLE
Faking native WrapPanel by keeping the items-per-row the same and enlarging the entire row

### ISSUE THREAD

**Issue by milos12345** [sbaeumlisberger/VirtualizingWrapPanel#56]
**Describe your issue**
I assume the actual behavior or native WrapPanel is not possible to virtualize so I have suggestion if this way it could be faked. Is it possible to keep number of items per row the same (like a grid), but then the entire row is enlarged to fit without leftover at the end of each row. I suspect that the scrolling might be jittery but maybe there is a way to measure the scrollbar per row count/position instead of readjusting the scroll-thumb/position for the actual scrollviewer extent that would otherwise change as the larger/smaller items are realized.

Something like this:

![image](https://github.com/sbaeumlisberger/VirtualizingWrapPanel/assets/5231547/36f5cf19-5706-44df-a551-6a95e5c4cfe8)

**Version Info**
Package Version 2.0.5
.NET Version: .NET Framework 4.8]
OS Version: Windows 11 Build 22631.3447]

**Comment by sbaeumlisberger** [comment]
I'm not quite sure what you want to achieve. The VirtualisingWrapPanel basically works like the native WrapPanel of WPF. As soon as no more items fit into a row, a wrap occurs. If you want the items to always fill the rows completely, you can set the [StretchItems](https://sbaeumlisberger.github.io/VirtualizingWrapPanel/api/WpfToolkit.Controls.VirtualizingWrapPanel.html#WpfToolkit_Controls_VirtualizingWrapPanel_StretchItems) property to True. If you want to always have the same number of items on a row, the items must all be the same size or the [ItemSize ](https://sbaeumlisberger.github.io/VirtualizingWrapPanel/api/WpfToolkit.Controls.VirtualizingWrapPanel.html#WpfToolkit_Controls_VirtualizingWrapPanel_ItemSize) property must be set.
