### ISSUE TITLE
In the case of Orientation="Vertical", the BringIndexIntoView method does not work correctly

### ISSUE THREAD

**Issue by GlodenBoy** [sbaeumlisberger/VirtualizingWrapPanel#58]
In the official example, when Orientation="Vertical" is set, the project can be jumped forward, but the position is incorrect when the project is retracted

Screen Recording Attachments:
[2024-05-14 17-30-01.zip](https://github.com/sbaeumlisberger/VirtualizingWrapPanel/files/15306316/2024-05-14.17-30-01.zip)

**Comment by sbaeumlisberger** [comment]
Fixed, new nuget package is available soon: https://www.nuget.org/packages/VirtualizingWrapPanel/2.0.6
