### ISSUE TITLE
Grid.IsSharedSizeScope

### ISSUE THREAD

**Issue by alrethomas** [sbaeumlisberger/VirtualizingWrapPanel#59]
Tried this wrap panel with data templates that build items items inside it that uses a Grid.IsSharedSizeScope. With normal wrap panel it works fine but with this one it don't seem to work. 
Just noticed now that the problem appears when I use the provided VirtualizingItemsControl. Using the normal ItemsControl made the wrap panel unusably slow. Using VirtualizingItemsControl seems to be faster but seems to change the layout.

**Comment by alrethomas** [comment]
Just noticed now that the problem appears when I use the provided VirtualizingItemsControl. Using the normal ItemsControl made the wrap panel unusably slow.

**Comment by sbaeumlisberger** [comment]
Could not reproduce. Note that only the currently realised elements (visible or in the cache) are part of the calculation.

**Comment by sbaeumlisberger** [comment]
close due to inactivity
