### ISSUE TITLE
Scroll issue when filter

### ISSUE THREAD

**Issue by Plinary** [sbaeumlisberger/VirtualizingWrapPanel#6]
First of all, Thank you for sharing the source code.
and sorry for my english.

I found issue when scroll height change a lot because of filtering.

Reproduce Step with Sample
1. Scroll down to the end, and scroll up slightly.
![image](https://user-images.githubusercontent.com/16220457/92281707-27e85a00-ef37-11ea-950e-475c67389bb8.png)
2. copy and paste (not typing)  "4900" to Filter (>). (make number of item 5000 to 100 suddenly)
3. no item shown
![image](https://user-images.githubusercontent.com/16220457/92281797-5d8d4300-ef37-11ea-9f2a-f42753a91ca9.png)
4. after wheel up or down, item appear.
\
\
\
\
\
After debugging, I find `Offset` variable is not change after filter.
`Offset` is bigger than `Extent`, so `GetRowIndex`, `UpdateItemRange` return wrong value.
this make all item disappear in panel
\
I modifed code like below.
```c#
protected override Size MeasureOverride(Size availableSize) // VirtualizingPanelBase.cs
{
..............................
           // added
           double rateX = 0;
            double rateY = 0;
            if (Extent.Height > 0 && Extent.Width > 0)
            {
                rateX = (Offset.X / Extent.Height);
                rateY = (Offset.Y / Extent.Height);
            }

            // original code
            if (groupItem != null)
            {
                Extent = extent;
                Offset = groupItem.Constraints.Viewport.Location;
                Viewport = groupItem.Constraints.Viewport.Size;
                CacheLength = groupItem.Constraints.CacheLength;
                CacheLengthUnit = groupItem.Constraints.CacheLengthUnit; // can be Item or Pixel
            }
            else
            {
                UpdateScrollInfo(desiredSize, extent);
                CacheLength = GetCacheLength(ItemsOwner);
                CacheLengthUnit = GetCacheLengthUnit(ItemsOwner); // can be Page, Item or Pixel
            }

            // added
            Offset = new Point(rateX * Extent.Width, Math.Min(rateY * Extent.Height, Extent.Height - Viewport.Height));
```
With this code, I get result after reproduce step 2
![image](https://user-images.githubusercontent.com/16220457/92282730-33d51b80-ef39-11ea-86df-57853e4ea5b7.png)

I hope this code helps you

**Comment by sbaeumlisberger** [comment]
Hello, thanks for reporting this bug. I was able to reproduce it and will fix it now.

**Comment by sbaeumlisberger** [comment]
I have commited a fix right now. I'll be releasing a new nuget package towards the end of the month.

**Comment by sbaeumlisberger** [comment]
Just published the NuGet Package: https://www.nuget.org/packages/VirtualizingWrapPanel/1.5.2
