### ISSUE TITLE
Items disappear from top row while using grouping

### ISSUE THREAD

**Issue by dlangell** [sbaeumlisberger/VirtualizingWrapPanel#61]
I've detected an oddity in the latest version (2.0.6) that was not present in the previous version I was using (1.5.7).  It can be seen in the sample application.  Go to the Grouping tab, change the Cache Unit to Item, and the Cache Length to something a little smaller (like 3,3) for simplicity.  Start clicking on the down arrow on the vertical scroll bar.  At some point when the top row of items is only partially visible, the beginning items in that row will disappear and you will only see the last items (the number of which is equal to the Cache Length) which are now shifted all the way to left with white space to the end of the row.  So with the parameters I provided, if you had 8 items visible per row with a Cache Length of 3,3, the first 5 items from the row will disappear and you will only see the last 3 items shifted to the left of the list.  As you continue to scroll down, items will continue to disappear in this manner for subsequent rows.  All rows after that still contain the full number of items to fill out the entire row.  This only seems to happen while using grouping.  If grouping is not enabled, it functions normally and the items do not disappear.

![WrapPanel](https://github.com/sbaeumlisberger/VirtualizingWrapPanel/assets/25904574/325a830a-c19b-4c75-bf71-7e749512a1f0)

**Version Info**
Package Version 2.0.6
.NET Version: .NET Framework 4.8
OS Version: Windows 11 23H2 Build 22631.3737

**Comment by sbaeumlisberger** [comment]
Fixed in Version 2.0.7: https://www.nuget.org/packages/VirtualizingWrapPanel/2.0.7

**Comment by dlangell** [comment]
Thanks for the quick fix.  That seems to have done the job up top.  However, I do now see slightly similar behavior at the bottom of the list when scrolling down.  It's not as consistent and is much less noticeable.  It also seems to take finding a certain window size before it happens.  And the visible items don't shift over to the left.  There's just a partially visible row of Cache Length size that doesn't fill out completely until you scroll down a bit farther.  After that, all rows seem to be fine.  Like I said, it's not as noticeable and isn't as big of a deal.  But thought I would still point it out.

In this screen shot, the 3 partially visible items at the bottom are items 25-27.  So items 28-30 don't appear until you scroll a little farther down.

![WrapPanel_Bottom](https://github.com/sbaeumlisberger/VirtualizingWrapPanel/assets/25904574/cd6a8890-13dc-4058-abed-c2bcbf87a786)

**Comment by sbaeumlisberger** [comment]
Thanks for reporting. Should be fixed in 2.0.9 (just uploaded)

**Comment by dlangell** [comment]
Sorry to be a pest, but that's actually much, much worse.  Now there's actually large chucks of white space at the bottom of each group that grow and shrink.  In this screenshot, Group 1 has 100 items and there's lots of room available to show more.  But only 11 are being shown until you keep scrolling down.

![WrapPanel_ExtraSpace](https://github.com/sbaeumlisberger/VirtualizingWrapPanel/assets/25904574/ab8b0dd9-303b-44bc-8e3e-4353ab4d52fc)

**Comment by sbaeumlisberger** [comment]
You are right! I hope it is really fixed now: https://www.nuget.org/packages/VirtualizingWrapPanel/2.0.10

**Comment by dlangell** [comment]
I think that did the trick.  I'm not seeing any extra white space now at the top or bottom of groups.  I'll continue to test my application and let you know if I see otherwise.  Thanks again for making the changes and for your quick response!
