### ISSUE TITLE
Listview  - Slow when at top of scrollview

### ISSUE THREAD

**Issue by VM-KTO** [sbaeumlisberger/VirtualizingWrapPanel#69]
I have a bunch of images I show through this wrappanel and everything except for this one situation is really fast and awesome.

I have a sort method that sorts which images to see and changes them a bit, and when I am at the bottom of my listview or in the middle, it's instant to sort and show items, but when I am at the top of the scrollview or if there are not enough items to even scroll and I sort and then there are enough items to scroll through it is crazy slow. It makes no sense to me, I have tested that the sort is not the issue.

What gives ?

Edit: I think this is actually an issue with the main wrappanel implementation, is there anything I can do to alleviate this issue through this implementation? 

Edit 2:
And when I do "Filter (Number >)" in your example it's instant..

Edit 3:
I just tried to change my items to a border with a background and now it's instant, I think it's something to do with WPF BitmapSource or bitmap rendering in general, I just can't get it to make sense that that it's different when I am on the top..

All versions, using .netframework 4.8

**Comment by sbaeumlisberger** [comment]
Based on the information you provided, it seems to be related to how you render the bitmaps, so I will close this issue. Let me know if you find a problem with the VirtualisingWrapPanel and I'll be happy to take a look.
