### ISSUE TITLE
The layout is completely messed up when grouping items in a vertical layout

### ISSUE THREAD

**Issue by lailablomme** [sbaeumlisberger/VirtualizingWrapPanel#70]
The layout is completely messed up when grouping items in a vertical layout. It doesn't seem to support this. I think it's only the position of the group items itself that is wrong.

**Version Info**
Package Version: 2.1.0 (I downloaded the latest source code)
.NET Version: 6
![screenshot virtualizingwrappanel](https://github.com/user-attachments/assets/40e6d296-47f5-41b5-bcb5-3ba5d3688764)

**Comment by lailablomme** [comment]
I've since found out that I need to use both `<ListView.ItemsPanel>` and `<ListView.GroupStyle><GroupStyle><GroupStyle.Panel>`, but even then using a `VirtualizingWrapPanel `for both renders weird results compared to using a regular `WrapPanel`.

**Comment by sbaeumlisberger** [comment]
If you want to get a vertical list of groups, you need to use a VirtualizingStackPanel as the GroupStyle.Panel and the VirtualizingWrapPanel as the ItemsPanel.

You can find an example in the [Getting started document](https://github.com/sbaeumlisberger/VirtualizingWrapPanel/blob/master/src/VirtualizingWrapPanel/docfx/docs/getting-started.md#grouping). You can also have a look at the [sample application](https://github.com/sbaeumlisberger/VirtualizingWrapPanel/blob/master/SamplesApplication.md).

**Comment by lailablomme** [comment]
Thanks, I did that, and it works, but the VirtualizingWrapPanel doesn't wrap vertically anymore -- I must scroll vertically instead of horizontally:

Without grouping:
![listview without grouping](https://github.com/user-attachments/assets/c28593b4-9a5f-4044-80a8-db9aac970d63)

With grouping:
![listview with grouping](https://github.com/user-attachments/assets/ce847034-ac35-4767-a19d-b856ad3c47d3)

Also, it doesn't seem to virtualize too much, as it takes quite some seconds before it loads.

**Comment by sbaeumlisberger** [comment]
Since this works well in my sample application, I need more information (e.g. code snippets) to help.

**Comment by sbaeumlisberger** [comment]
Hi, first of all make sure that the orientation of the VirtualizingWrapPanel is the opposite of the VirtualizingStackPanel's orientation. 

If `VirtualizingStackPanel.Orientation` is `Vertical` and `VirtualizingWrapPanel.Orientation` is `Horizontal` you can scroll vertically through the groups and the VirtualizingWrapPanel  wraps the items at the right end of the viewport.

If `VirtualizingStackPanel.Orientation` is `Horizontal` and `VirtualizingWrapPanel.Orientation` is `Vertical` you can scroll horizontally through the groups and the VirtualizingWrapPanel  wraps the items at the bottom of the viewport.

Any other combination is not supported.

The default orientation of the VirtualizingWrapPanel is `Horizontal`. So you need to either change the orientation of  your VirtualizingStackPanel or VirtualizingWrapPanel  to `Vertical`.

**Comment by sbaeumlisberger** [comment]
I have the updated the documentation to make this more clear.

**Comment by lailablomme** [comment]
I've dug deeper into this and I can get the layout right, but the `VirtualizingStackPanel `isn't virtualizing when I set it to `Horizontal`. It does virtualize when I set it to `Vertical`. So this is not on your account anymore, but any help is ofcourse greately appreciated ;-)

**Comment by lailablomme** [comment]
I finally got it working! It's 2:44am here now and we're two weeks of fucking around later :-P 

I don't known why, but I started getting in trouble with the `VirtualizingWrapPanel ` constantly flickering up to the point it became unusable and when I breaked the program I saw in the stack trace that it was constantly measuring and arranging. So I reckoned it had trouble sticking to a constant item size so I set the `ItemSize` property of the `VirtualizingWrapPanel` to something constant. And now all of a sudden all of my problems are gone and everything is working like I've been searching for for two weeks now :-) Both the `VirtualizingStackPanel` and the `VirtualizingWrapPanel `are virtualizing and I've got the layout that I want. I also had to set the `Height `of the `VirtualizingWrapPanel `manually because it doesn't account for my grouping headers all by itself. 

The only quirk left now is that somewhere halfway scrolling through the items horizontally (when browsing `Windows\System32`, grouped by file type) the scrollbar changes it's scaling drastically because I've scrolled up to the `.DLL`s-group of items which is a lot larger than all the others. I wonder how I'm going to fix that.

If you're interested in taking a look or playing around with it a bit, the full source code is at https://sourceforge.net/p/laila-shell/code/ci/master/tree/ , but beware, it's way pre-release and still a work in progress, so you might hit some bumps.

**Comment by sbaeumlisberger** [comment]
Glad to hear you got it working. I think the scrollbar "scaling" changes are caused by the VirtualisingStackPanel and I fear there's not much you can do about that, because it just doesn't know how big the not yet realized groups are. 

If you think some of your problems, such as the constant measuring and arranging, are caused by the VirtualizingWrapPanel, I would appreciate it if you would open new issues with clear steps to reproduce or a minimal sample project.
