### ISSUE TITLE
Allow usage of the VirtualizingWrapPanel without an ItemsControl (non-virtualised)

### ISSUE THREAD

**Issue by valhentai** [sbaeumlisberger/VirtualizingWrapPanel#73]
When using the VirtualizingWrapPanel, I have a null pointer Exception on the ItemContainerGenerator getter on first measure of the panel

```
System.NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet.
   à WpfToolkit.Controls.VirtualizingPanelBase.get_ItemContainerGenerator()
   à WpfToolkit.Controls.VirtualizingWrapPanel.get_ItemContainerManager()
   à WpfToolkit.Controls.VirtualizingWrapPanel.MeasureOverride(Size availableSize)
   à System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   à System.Windows.UIElement.Measure(Size availableSize)
   ```
   
   I already used this panel elsewhere in my application and I din't had any problems.  
   I think the difference is that in this case, I don't populate the panel throuh an ItemsControls. I use the panel directly in the XAML and fill it directly with visuals.
   
   First I thought it was a WPF bug that I already know where you have to get the children collection to make WP create the ItemContainerGenerator. But I saw in the source code that this is already taken care of. 
   
``` 
  // The ItemContainerGenerator is null until InternalChildren is accessed at least one time.
_ = InternalChildren;
_itemContainerGenerator = base.ItemContainerGenerator.GetItemContainerGeneratorForPanel(this);
```

I just want to use the Stretching feature of the VirtualizingWrapPanel which does not exist on the standard WrapPanel. That why I am using a virtualizing panel in a non virtualizing situation.  
I tried to set IsVirtualizing to False but it does not solve the problem.

**Version Info**
Package Version: 2.1.0
 .NET Framework 4.7.2

**Comment by sbaeumlisberger** [comment]
Unfortunately, non-virtualised usage of the VirtualisingWrapPanel is not currently supported. The implementation expects it to be used with an ItemsControl. I will see if I can provide a quick solution, but I fear it will be quite complex.

**Comment by valhentai** [comment]
@sbaeumlisberger Thanks for your feedback. I managed to make it work by using it in in a ItemsControl. This will do.

**Comment by sbaeumlisberger** [comment]
Glad you found a solution. As expected, this would be a rather complex change without much benefit in my opinion. So for now I just added a more meaningful exception.
